server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
logging:
  level:
    org.tron: DEBUG
    tk.mybatis: DEBUG
    org.springframework: WARN
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/val_signing?characterEncoding=UTF-8
    username: root
    password: root
  redis:
    host: 39.99.169.210
    port: 6379
    password: redis123app
    timeout: 7000
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  type-aliases-package: org.tron.kms.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  mappers: org.tron.kms.util.MyMapper
  not-empty: false
  identity: MYSQL